@extends('layouts.app')
@section('content')
<x-ui.page-header title="Подписка" description="Выберите тариф и сумму оплаты — срок подписки рассчитывается по дневной стоимости." />
<x-ui.card><p class="text-sm text-muted">Текущий тариф</p><p class="mt-1 text-lg font-semibold">{{ $user->subscription_plan->label() }}</p>
@if($subscription?->status === \App\Enums\SubscriptionStatus::Active)<p class="mt-2 text-sm text-muted">Подписка действует по {{ $subscription->ends_on->format('d.m.Y') }} включительно.</p>
@elseif($subscription?->status === \App\Enums\SubscriptionStatus::Pending)<x-ui.alert type="warning" class="mt-4">Квитанция принята и ожидает проверки администратора. Доступ откроется после подтверждения оплаты.</x-ui.alert>
@elseif($subscription?->status === \App\Enums\SubscriptionStatus::Rejected)<x-ui.alert type="danger" class="mt-4">Предыдущая заявка отклонена: {{ $subscription->paymentRequest?->rejection_reason }}. Исправьте данные и отправьте новую заявку.</x-ui.alert>
@elseif($user->organization?->status === 'pending')<p class="mt-2 text-sm text-muted">Ваша организация ожидает подтверждения администратора.</p>
@else<x-ui.alert type="warning" class="mt-4">Требуется активная платная подписка.</x-ui.alert>@endif</x-ui.card>
@if($user->isCustomer() && $user->organization?->status === 'active' && $subscription?->status !== \App\Enums\SubscriptionStatus::Pending)
<x-ui.card class="mt-5"><h2 class="text-lg font-semibold">Оплата подписки</h2><p class="mt-1 text-sm text-muted">Сумма должна быть кратна дневной стоимости выбранного тарифа.</p>
@if($plans->isNotEmpty() && $paymentMethods->isNotEmpty())<form method="post" action="{{ route('subscription.requests.store') }}" enctype="multipart/form-data" class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3" data-subscription-calculator>@csrf
<x-ui.select name="plan" label="Тариф" required data-subscription-plan><option value="">Выберите тариф</option>@foreach($plans as $plan)<option value="{{ $plan->plan->value }}" data-daily-price="{{ $plan->daily_price }}" @selected(old('plan') === $plan->plan->value)>{{ $plan->plan->label() }} · {{ $plan->daily_price }} TJS/день</option>@endforeach</x-ui.select><x-ui.input name="amount" type="number" step="0.01" min="0.01" label="Сумма оплаты, TJS" value="{{ old('amount') }}" required data-subscription-amount /><x-ui.select name="payment_method" label="Метод оплаты" required><option value="">Выберите метод</option>@foreach($paymentMethods as $method)<option value="{{ $method->method->value }}" @selected(old('payment_method') === $method->method->value)>{{ $method->method->label() }} · {{ $method->wallet_number }} · {{ $method->wallet_owner_name }}</option>@endforeach</x-ui.select>
<x-ui.input name="sender_wallet_number" type="tel" label="Ваш кошелёк отправителя" hint="Необязательно. Формат: +992XXXXXXXXX" value="{{ old('sender_wallet_number') }}" /><x-ui.input name="sender_wallet_owner_name" label="Имя владельца кошелька отправителя" hint="Необязательно." value="{{ old('sender_wallet_owner_name') }}" /><x-ui.input name="transferred_on" label="Дата перевода" hint="Формат: ДД/ММ/ГГГГ" value="{{ old('transferred_on', now('Asia/Dushanbe')->format('d/m/Y')) }}" placeholder="ДД/ММ/ГГГГ" required /><x-ui.input name="receipt" type="file" label="Квитанция" accept="image/jpeg,image/png,image/webp,application/pdf" hint="JPEG, PNG, WebP или PDF, до 10 МБ." required />
<div class="md:col-span-2 xl:col-span-3"><x-ui.alert type="warning"><span data-subscription-days>Выберите тариф и укажите сумму, чтобы увидеть срок подписки.</span></x-ui.alert></div><div class="md:col-span-2 xl:col-span-3"><x-ui.button>Отправить квитанцию на проверку</x-ui.button></div></form>
@else<x-ui.alert type="warning" class="mt-4">Администратор ещё не настроил доступный способ оплаты.</x-ui.alert>@endif</x-ui.card>
@endif
@endsection
