@extends('layouts.app')
@section('content')
<x-ui.page-header title="Подписка" description="Выберите тариф и срок подписки — сумма оплаты рассчитается автоматически." />
<x-ui.card><p class="text-sm text-muted">Текущий тариф</p><p class="mt-1 text-lg font-semibold">{{ $user->subscription_plan->label() }}</p>
@if($subscription?->status === \App\Enums\SubscriptionStatus::Active)<p class="mt-2 text-sm text-muted">Подписка действует по {{ $subscription->ends_on->format('d.m.Y') }} включительно.</p>
@elseif($subscription?->status === \App\Enums\SubscriptionStatus::Pending)<x-ui.alert type="warning" class="mt-4">Квитанция принята и ожидает проверки администратора. Доступ откроется после подтверждения оплаты.</x-ui.alert>
@elseif($subscription?->status === \App\Enums\SubscriptionStatus::Rejected)<x-ui.alert type="danger" class="mt-4">Предыдущая заявка отклонена: {{ $subscription->paymentRequest?->rejection_reason }}. Исправьте данные и отправьте новую заявку.</x-ui.alert>
@elseif($user->organization?->status === 'pending')<p class="mt-2 text-sm text-muted">Ваша организация ожидает подтверждения администратора.</p>
@else<x-ui.alert type="warning" class="mt-4">Требуется активная платная подписка.</x-ui.alert>@endif</x-ui.card>
@if($user->isCustomer() && $user->organization?->status === 'active' && $subscription?->status !== \App\Enums\SubscriptionStatus::Pending)
<x-ui.card class="mt-5"><h2 class="text-lg font-semibold">Оплата подписки</h2><p class="mt-1 text-sm text-muted">Сумма оплаты рассчитывается автоматически по дневной стоимости тарифа.</p>
@if($plans->isNotEmpty() && $paymentMethods->isNotEmpty())<form method="post" action="{{ route('subscription.requests.store') }}" enctype="multipart/form-data" class="mt-5 space-y-5" data-subscription-calculator>@csrf
<fieldset><legend class="text-sm font-medium text-slate-700">Тариф</legend><div class="mt-2 grid gap-3 md:grid-cols-2">@foreach($plans as $plan)<label data-subscription-choice @class(['block cursor-pointer rounded-panel border p-4 transition focus-within:outline-2 focus-within:outline-offset-2 focus-within:outline-brand-600', 'border-danger' => $errors->has('plan'), 'border-brand-600 bg-brand-50' => old('plan', 'base') === $plan->plan->value, 'border-slate-300 bg-white hover:border-brand-500' => old('plan', 'base') !== $plan->plan->value])><input class="sr-only" type="radio" name="plan" value="{{ $plan->plan->value }}" data-daily-price="{{ $plan->daily_price }}" data-subscription-plan @checked(old('plan', 'base') === $plan->plan->value)><span class="block font-semibold">{{ $plan->plan->label() }}</span><span class="mt-1 block text-sm text-muted">{{ $plan->daily_price }} TJS/день</span></label>@endforeach</div>@error('plan')<p class="mt-1.5 text-xs text-danger">{{ $message }}</p>@enderror</fieldset>
<fieldset><legend class="text-sm font-medium text-slate-700">Срок подписки</legend><div class="mt-2 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach([['term' => \App\Enums\SubscriptionTerm::TenDays, 'days' => 10], ['term' => \App\Enums\SubscriptionTerm::Month, 'days' => 30], ['term' => \App\Enums\SubscriptionTerm::SixMonths, 'days' => 180], ['term' => \App\Enums\SubscriptionTerm::Year, 'days' => 365]] as $option)@php($term = $option['term'])<label data-subscription-choice @class(['block cursor-pointer rounded-panel border p-4 transition focus-within:outline-2 focus-within:outline-offset-2 focus-within:outline-brand-600', 'border-danger' => $errors->has('term'), 'border-brand-600 bg-brand-50' => old('term', \App\Enums\SubscriptionTerm::Month->value) === $term->value, 'border-slate-300 bg-white hover:border-brand-500' => old('term', \App\Enums\SubscriptionTerm::Month->value) !== $term->value])><input class="sr-only" type="radio" name="term" value="{{ $term->value }}" data-subscription-term data-days="{{ $option['days'] }}" @checked(old('term', \App\Enums\SubscriptionTerm::Month->value) === $term->value)><span class="block font-semibold">{{ $term->label() }}</span><span class="mt-1 block text-sm text-muted">{{ $option['days'] }} дней</span></label>@endforeach</div>@error('term')<p class="mt-1.5 text-xs text-danger">{{ $message }}</p>@enderror</fieldset>
<fieldset><legend class="text-sm font-medium text-slate-700">Метод оплаты</legend><div class="mt-2 grid gap-3 md:grid-cols-3">@foreach($paymentMethods as $method)<label data-subscription-choice @class(['block cursor-pointer rounded-panel border p-4 transition focus-within:outline-2 focus-within:outline-offset-2 focus-within:outline-brand-600', 'border-danger' => $errors->has('payment_method'), 'border-brand-600 bg-brand-50' => old('payment_method', 'dc') === $method->method->value, 'border-slate-300 bg-white hover:border-brand-500' => old('payment_method', 'dc') !== $method->method->value])><input class="sr-only" type="radio" name="payment_method" value="{{ $method->method->value }}" data-subscription-payment-method @checked(old('payment_method', 'dc') === $method->method->value)><span class="block font-semibold">{{ $method->method->label() }}</span><span class="mt-1 block break-all text-sm text-muted">{{ $method->wallet_number }}</span><span class="mt-1 block text-sm text-muted">{{ $method->wallet_owner_name }}</span></label>@endforeach</div>@error('payment_method')<p class="mt-1.5 text-xs text-danger">{{ $message }}</p>@enderror</fieldset>
<x-ui.alert type="warning"><p class="font-semibold">Сумма оплаты, TJS: <output data-subscription-total aria-live="polite">—</output></p><p class="mt-1" data-subscription-days>Выберите тариф и срок подписки.</p></x-ui.alert>
<x-ui.input name="transferred_on" label="Дата перевода" hint="Формат: ДД/ММ/ГГГГ" value="{{ old('transferred_on', now('Asia/Dushanbe')->format('d/m/Y')) }}" placeholder="ДД/ММ/ГГГГ" required />
<x-ui.input name="receipt" type="file" label="Квитанция" accept="image/jpeg,image/png,image/webp,application/pdf" hint="Загрузите квитанцию в формате JPEG, PNG, WebP или PDF, до 10 МБ." required />
<x-ui.button>Отправить заявку на проверку</x-ui.button></form>
@else<x-ui.alert type="warning" class="mt-4">Администратор ещё не настроил доступный способ оплаты.</x-ui.alert>@endif</x-ui.card>
@endif
@endsection
