<?php

use App\Http\Controllers\Admin\CategoryReviewController;
use App\Http\Controllers\Admin\OrganizationDirectoryController;
use App\Http\Controllers\Admin\SupplierImportProfileController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AdminSubscriptionController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CatalogController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PartnerController;
use App\Http\Controllers\PaymentReceiptController;
use App\Http\Controllers\PriceListImportController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\SubscriptionRequestController;
use App\Http\Controllers\SupplierInvitationController;
use App\Http\Controllers\TwoFactorController;
use App\Services\PhoneOtpService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/', fn (Request $request) => redirect()->route($request->user()?->defaultLandingRouteName() ?? 'catalog'));
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'loginForm'])->name('login');
    Route::post('/login/phone', [AuthController::class, 'sendLoginOtp'])->name('login.otp.send');
    Route::get('/login/phone/verify', [AuthController::class, 'loginOtpForm'])->name('login.otp.form');
    Route::post('/login/phone/verify', [AuthController::class, 'verifyLoginOtp'])->name('login.otp.verify');
    Route::get('/login/phone/session-confirmation', [AuthController::class, 'sessionConfirmationForm'])->name('login.session.confirmation');
    Route::post('/login/phone/session-confirmation', [AuthController::class, 'confirmSessionReplacement'])->name('login.session.confirm');
    Route::post('/login/phone/session-confirmation/cancel', [AuthController::class, 'cancelSessionReplacement'])->name('login.session.cancel');
    Route::post('/login/phone/resend', fn (Request $request, AuthController $controller, PhoneOtpService $otpService) => $controller->resend($request, $otpService, 'login'))->name('login.otp.resend');
    Route::get('/admin/login', [AuthController::class, 'adminLoginForm'])->name('admin.login');
    Route::post('/admin/login', [AuthController::class, 'adminLogin'])->middleware('throttle:5,1')->name('admin.login.authenticate');
    Route::get('/provider/login', [AuthController::class, 'providerLoginForm'])->name('provider.login');
    Route::post('/provider/login/phone', [AuthController::class, 'sendSupplierLoginOtp'])->name('provider.otp.send');
    Route::get('/provider/login/phone/verify', [AuthController::class, 'supplierLoginOtpForm'])->name('provider.otp.form');
    Route::post('/provider/login/phone/verify', [AuthController::class, 'verifySupplierLoginOtp'])->name('provider.otp.verify');
    Route::get('/provider/login/phone/session-confirmation', [AuthController::class, 'supplierSessionConfirmationForm'])->name('provider.session.confirmation');
    Route::post('/provider/login/phone/session-confirmation', [AuthController::class, 'confirmSupplierSessionReplacement'])->name('provider.session.confirm');
    Route::post('/provider/login/phone/session-confirmation/cancel', [AuthController::class, 'cancelSupplierSessionReplacement'])->name('provider.session.cancel');
    Route::post('/provider/login/phone/resend', fn (Request $request, AuthController $controller, PhoneOtpService $otpService) => $controller->resendSupplier($request, $otpService, 'login'))->name('provider.otp.resend');
    Route::get('/provider/register', [AuthController::class, 'supplierRegisterForm'])->name('provider.register');
    Route::post('/provider/register', [AuthController::class, 'supplierRegister'])->name('provider.register.phone');
    Route::get('/provider/register/name', [AuthController::class, 'supplierRegistrationDetailsForm'])->name('provider.register.details.form');
    Route::post('/provider/register/name', [AuthController::class, 'storeSupplierRegistrationDetails'])->name('provider.register.details.store');
    Route::get('/provider/register/verify', [AuthController::class, 'supplierRegisterOtpForm'])->name('provider.register.otp.form');
    Route::post('/provider/register/verify', [AuthController::class, 'verifySupplierRegistrationOtp'])->name('provider.register.otp.verify');
    Route::post('/provider/register/resend', fn (Request $request, AuthController $controller, PhoneOtpService $otpService) => $controller->resendSupplier($request, $otpService, 'registration'))->name('provider.register.otp.resend');
    Route::get('/register', [AuthController::class, 'registerForm'])->name('register');
    Route::post('/register', [AuthController::class, 'register'])->name('register.phone');
    Route::get('/register/name', [AuthController::class, 'registrationDetailsForm'])->name('register.details.form');
    Route::post('/register/name', [AuthController::class, 'storeRegistrationDetails'])->name('register.details.store');
    Route::get('/register/verify', [AuthController::class, 'registerOtpForm'])->name('register.otp.form');
    Route::post('/register/verify', [AuthController::class, 'verifyRegistrationOtp'])->name('register.otp.verify');
    Route::post('/register/resend', fn (Request $request, AuthController $controller, PhoneOtpService $otpService) => $controller->resend($request, $otpService, 'registration'))->name('register.otp.resend');
});
Route::post('/logout', [AuthController::class, 'logout'])->middleware('auth')->name('logout');
Route::middleware('auth')->group(function () {
    Route::get('/subscription', [SubscriptionController::class, 'create'])->name('subscription.create');
    Route::post('/subscription/requests', [SubscriptionRequestController::class, 'store'])->name('subscription.requests.store');
    Route::get('/payment-requests/{paymentRequest}/receipt', [PaymentReceiptController::class, 'show'])->name('payment-requests.receipt');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::post('/profile/phone', [ProfileController::class, 'sendPhoneChange'])->name('profile.phone.send');
    Route::get('/profile/phone/verify', [ProfileController::class, 'phoneChangeForm'])->name('profile.phone.verify');
    Route::post('/profile/phone/verify', [ProfileController::class, 'confirmPhoneChange'])->name('profile.phone.confirm');
    Route::patch('/profile/organization', [ProfileController::class, 'updateOrganization'])->name('profile.organization.update');
    Route::get('/two-factor', [TwoFactorController::class, 'enroll'])->name('two-factor.enroll');
    Route::post('/two-factor', [TwoFactorController::class, 'confirm'])->middleware('throttle:5,1')->name('two-factor.confirm');
    Route::post('/two-factor/recovery', [TwoFactorController::class, 'recovery'])->middleware('throttle:5,1')->name('two-factor.recovery');
});
Route::middleware(['auth', 'active', 'two-factor-confirmed'])->group(function () {
    Route::middleware('role:pharmacy')->group(function () {
        Route::get('/partners', [PartnerController::class, 'index'])->name('partners.index');
        Route::post('/partners/phone', [PartnerController::class, 'linkPhone'])->middleware('throttle:10,1')->name('partners.phone');
        Route::post('/partners/code', [PartnerController::class, 'redeem'])->middleware('throttle:5,1')->name('partners.code');
        Route::patch('/partners/{supplier}/discount', [PartnerController::class, 'updateDiscount'])->name('partners.discount');
    });
    Route::middleware('role:wholesaler')->group(function () {
        Route::post('/supplier/invitations', [SupplierInvitationController::class, 'store'])->middleware('throttle:10,1')->name('supplier.invitations.store');
        Route::post('/supplier/invitations/{invitation}/revoke', [SupplierInvitationController::class, 'revoke'])->name('supplier.invitations.revoke');
    });
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/catalog', [CatalogController::class, 'index'])->name('catalog');
    Route::get('/catalog/search', [CatalogController::class, 'search'])->name('catalog.search');
    Route::get('/cart', [CartController::class, 'show'])->name('cart');
    Route::post('/cart/{offer}', [CartController::class, 'add'])->name('cart.add');
    Route::patch('/cart/items/{item}', [CartController::class, 'update'])->name('cart.update');
    Route::post('/cart/checkout', [CartController::class, 'checkout'])->name('cart.checkout');
    Route::get('/orders', [OrderController::class, 'index'])->name('orders.index');
    Route::get('/orders/{order}', [OrderController::class, 'show'])->name('orders.show');
    Route::patch('/orders/{order}/status', [OrderController::class, 'status'])->name('orders.status');
    Route::get('/price-list-imports', [PriceListImportController::class, 'index'])->name('price-list-imports.index');
    Route::post('/price-list-imports', [PriceListImportController::class, 'store'])->name('price-list-imports.store');
    Route::get('/price-list-imports/{import}', [PriceListImportController::class, 'show'])->name('price-list-imports.show');
    Route::get('/price-list-imports/{import}/download', [PriceListImportController::class, 'download'])->name('price-list-imports.download');
    Route::get('/price-list-imports/{import}/categorization-report', [PriceListImportController::class, 'categorizationReport'])->name('price-list-imports.categorization-report');
    Route::post('/price-list-imports/{import}/retry', [PriceListImportController::class, 'retry'])->name('price-list-imports.retry');
    Route::prefix('admin')->middleware('role:admin')->group(function () {
        Route::get('/', [AdminController::class, 'index'])->name('admin.index');
        Route::post('/organizations/{organization}/approve', [AdminController::class, 'approve'])->name('admin.approve');
        Route::post('/suppliers', [AdminController::class, 'storeSupplier'])->name('admin.suppliers.store');
        Route::get('/users', [AdminController::class, 'users'])->name('admin.users');
        Route::get('/pharmacies', [OrganizationDirectoryController::class, 'pharmacies'])->name('admin.pharmacies.index');
        Route::get('/pharmacies/{organization}', [OrganizationDirectoryController::class, 'showPharmacy'])->name('admin.pharmacies.show');
        Route::get('/pharmacies/{organization}/edit', [OrganizationDirectoryController::class, 'editPharmacy'])->name('admin.pharmacies.edit');
        Route::patch('/pharmacies/{organization}', [OrganizationDirectoryController::class, 'updatePharmacy'])->name('admin.pharmacies.update');
        Route::patch('/pharmacies/{organization}/accounts/{user}', [OrganizationDirectoryController::class, 'updatePharmacyAccount'])->name('admin.pharmacies.accounts.update');
        Route::post('/pharmacies/{organization}/archive', [OrganizationDirectoryController::class, 'archivePharmacy'])->name('admin.pharmacies.archive');
        Route::get('/providers', [OrganizationDirectoryController::class, 'providers'])->name('admin.providers.index');
        Route::get('/providers/{organization}', [OrganizationDirectoryController::class, 'showProvider'])->name('admin.providers.show');
        Route::get('/providers/{organization}/edit', [OrganizationDirectoryController::class, 'editProvider'])->name('admin.providers.edit');
        Route::patch('/providers/{organization}', [OrganizationDirectoryController::class, 'updateProvider'])->name('admin.providers.update');
        Route::patch('/providers/{organization}/accounts/{user}', [OrganizationDirectoryController::class, 'updateProviderAccount'])->name('admin.providers.accounts.update');
        Route::post('/providers/{organization}/archive', [OrganizationDirectoryController::class, 'archiveProvider'])->name('admin.providers.archive');
        Route::post('/users/{user}/block', [AdminController::class, 'toggleBlock'])->name('admin.block');
        Route::post('/users/{user}/phone', [AdminController::class, 'remediatePhone'])->name('admin.phone.remediate');
        Route::get('/subscriptions', [AdminSubscriptionController::class, 'index'])->name('admin.subscriptions.index');
        Route::post('/subscriptions', [AdminSubscriptionController::class, 'store'])->name('admin.subscriptions.store');
        Route::post('/subscriptions/{subscription}/cancel', [AdminSubscriptionController::class, 'cancel'])->name('admin.subscriptions.cancel');
        Route::get('/subscription-prices', [AdminSubscriptionController::class, 'prices'])->name('admin.subscription-prices.edit');
        Route::patch('/subscription-prices', [AdminSubscriptionController::class, 'updatePrices'])->name('admin.subscription-prices.update');
        Route::get('/subscription-payments', [AdminSubscriptionController::class, 'paymentRequests'])->name('admin.subscription-payments.index');
        Route::patch('/subscription-payments/methods', [AdminSubscriptionController::class, 'updatePaymentMethods'])->name('admin.subscription-payments.methods.update');
        Route::post('/subscription-payments/{paymentRequest}/review', [AdminSubscriptionController::class, 'reviewPayment'])->name('admin.subscription-payments.review');
        Route::get('/suppliers/{supplier}/import-profile', [SupplierImportProfileController::class, 'edit'])->name('admin.supplier-import-profiles.edit');
        Route::post('/suppliers/{supplier}/import-profile/sample', [SupplierImportProfileController::class, 'storeSample'])->name('admin.supplier-import-profiles.sample.store');
        Route::get('/suppliers/{supplier}/import-profile/sample-preview', [SupplierImportProfileController::class, 'samplePreview'])->name('admin.supplier-import-profiles.sample.preview');
        Route::put('/suppliers/{supplier}/import-profile', [SupplierImportProfileController::class, 'update'])->name('admin.supplier-import-profiles.update');
        Route::post('/price-list-imports/{import}/rows/{row}/override', [PriceListImportController::class, 'override'])->name('admin.price-list-imports.override');
        Route::get('/category-reviews', [CategoryReviewController::class, 'index'])->name('admin.category-reviews.index');
        Route::post('/medicines/{medicine}/categories/unlock', [CategoryReviewController::class, 'unlock'])->name('admin.medicines.categories.unlock');
    });
});
