@extends('layouts.app')
@section('content')
    <x-ui.page-header :title="$import->original_filename" :description="$import->supplier->name.' · загружен '. $import->created_at->format('d.m.Y H:i')">
        <x-slot:actions><div class="flex flex-wrap gap-2"><a href="{{ route('price-list-imports.download', $import) }}"><x-ui.button type="button" variant="secondary">Скачать исходник</x-ui.button></a><a href="{{ route('price-list-imports.categorization-report', $import) }}"><x-ui.button type="button" variant="secondary">CSV категорий</x-ui.button></a>@if($import->status === \App\Enums\PriceListImportStatus::Failed)<form method="post" action="{{ route('price-list-imports.retry', $import) }}">@csrf<x-ui.button>Повторить</x-ui.button></form>@endif</div></x-slot:actions>
    </x-ui.page-header>
    <div class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">
        @foreach(['total_rows' => 'Всего', 'valid_rows' => 'Корректные', 'warning_rows' => 'С предупреждением', 'error_rows' => 'Ошибки', 'skipped_rows' => 'Пропущены'] as $field => $label)<x-ui.card><p class="text-sm text-muted">{{ $label }}</p><p class="mt-1 text-2xl font-bold">{{ $import->{$field} }}</p></x-ui.card>@endforeach
    </div>
    @if($import->failure_message)<x-ui.alert type="danger" class="mt-6">{{ $import->failure_message }}</x-ui.alert>@endif
    <x-ui.alert type="success" class="mt-6">Обработка и публикация выполняются автоматически. Товары без назначенной категории также публикуются; категории можно уточнить позже.</x-ui.alert>
    @if($import->duplicate_of_import_id)<x-ui.alert type="warning" class="mt-4">Файл совпадает с успешно обработанным импортом № {{ $import->duplicate_of_import_id }}, но повторная обработка уже поставлена в очередь.</x-ui.alert>@endif
    <x-ui.card class="mt-6"><h2 class="font-bold">Снимок профиля</h2><p class="mt-2 text-sm text-muted">Лист: {{ $import->profile_snapshot['worksheet'] ?? 'первый' }} · начало данных: {{ $import->profile_snapshot['data_row'] }} · сопоставление: {{ $import->profile_snapshot['matching_strategy'] }}</p></x-ui.card>
    <form class="mt-6 flex flex-wrap items-end gap-3" method="get"><x-ui.select name="categorization_status" label="Статус категоризации"><option value="">Все</option><option value="matched" @selected(request('categorization_status') === 'matched')>Одна категория</option><option value="multi_matched" @selected(request('categorization_status') === 'multi_matched')>Несколько категорий</option><option value="attention_needed" @selected(request('categorization_status') === 'attention_needed')>Желательно уточнить</option><option value="uncategorized" @selected(request('categorization_status') === 'uncategorized')>Без категории</option><option value="manual_locked" @selected(request('categorization_status') === 'manual_locked')>Закреплено вручную</option></x-ui.select><x-ui.button type="submit" variant="secondary">Фильтровать</x-ui.button></form>
    <div class="mt-6 table-wrap"><table class="data-table"><thead><tr><th>Строка</th><th>Товар</th><th>Категории</th><th>Уверенность и основания</th><th>Результат</th></tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ $row->source_row }}</td><td>{{ $row->original_product_name ?? $row->parsed_values['name'] ?? '' }}</td><td><div class="flex flex-wrap gap-2">@forelse(collect($row->category_candidates ?? [])->where('decision', 'accepted') as $candidate)<span class="rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-800">{{ $candidate['label'] }} · {{ $candidate['confidence'] }}%</span>@empty<span class="text-muted">Не распознано</span>@endforelse</div>@if(auth()->user()->isAdmin() && in_array($row->categorization_status, ['attention_needed', 'uncategorized', 'manual_locked'], true))<form class="mt-3 flex flex-wrap items-end gap-2" method="post" action="{{ route('admin.price-list-imports.override', [$import, $row]) }}">@csrf<x-ui.select name="categories[]" label="Выбрать категории" multiple size="5">@foreach($productCategories as $category)<option value="{{ $category->code }}" @selected(in_array($category->code, $row->assigned_categories ?? [], true))>{{ $category->label }}</option>@endforeach</x-ui.select><x-ui.button variant="secondary">Сохранить набор</x-ui.button></form>@endif</td><td>@foreach($row->category_candidates ?? [] as $candidate)<p class="text-sm">{{ $candidate['label'] }}: {{ $candidate['confidence'] }}% — {{ $candidate['decision'] }}</p>@endforeach</td><td><span class="font-semibold">{{ $row->categorization_status ?? $row->disposition->value }}</span>@foreach($row->errors ?? [] as $error)<p class="text-sm text-danger">{{ $error }}</p>@endforeach @foreach($row->warnings ?? [] as $warning)<p class="text-sm text-warning">{{ $warning }}</p>@endforeach</td></tr>@empty<tr><td colspan="5">Строки ещё не обработаны.</td></tr>@endforelse</tbody></table></div>
    <div class="mt-4">{{ $rows->links() }}</div>
@endsection
