@extends('layouts.app')
@section('content')
<x-ui.page-header title="Профиль" description="Личные данные и рабочие настройки." />
<div class="grid gap-5 lg:grid-cols-2">
<x-ui.card><form method="post" action="{{ route('profile.update') }}" class="space-y-4">@csrf @method('PATCH')<x-ui.input name="name" label="Имя" :value="$user->name" required />@if($user->isAdmin())<x-ui.input name="email" type="email" label="Email" :value="$user->email" required /><x-ui.input name="password" type="password" label="Новый пароль" hint="Оставьте пустым, чтобы не менять." /><x-ui.input name="password_confirmation" type="password" label="Повторите пароль" />@endif<x-ui.select name="theme" label="Тема" :value="$user->theme"><option value="light">Светлая</option><option value="dark">Тёмная</option></x-ui.select><x-ui.button>Сохранить профиль</x-ui.button></form>@if(!$user->isAdmin())<form method="post" action="{{ route('profile.phone.send') }}" class="mt-5 space-y-4 border-t border-slate-200 pt-5">@csrf <x-ui.input name="phone" label="Новый телефон" hint="Изменение подтверждается кодом SMS." required autocomplete="tel" /><x-ui.button variant="secondary">Подтвердить новый телефон</x-ui.button></form>@endif</x-ui.card>
@if($organization)<x-ui.card><form method="post" action="{{ route('profile.organization.update') }}" class="space-y-4">@csrf @method('PATCH')<x-ui.input name="name" label="Организация" :value="$organization->name" required /><x-ui.input name="city" label="Город" :value="$organization->city" />@if($user->isWholesaler())<x-ui.select name="active_trade_mode" label="Рабочий режим" :value="$user->active_trade_mode?->value"><option value="supplier">Поставщик</option><option value="buyer">Покупатель</option></x-ui.select><x-ui.input name="minimum_order" type="number" label="Минимальный заказ" :value="$organization->minimum_order" /><x-ui.input name="delivery_conditions" label="Условия доставки" :value="$organization->delivery_conditions" /><x-ui.input name="contact_name" label="Контактное лицо" :value="$organization->contact_name" /><x-ui.input name="contact_email" type="email" label="Контактный email" :value="$organization->contact_email" /><x-ui.input name="whatsapp_phone" label="WhatsApp" :value="$organization->whatsapp_phone" /><x-ui.textarea name="additional_phones" label="Дополнительные телефоны" :value="implode("\n", $organization->additional_phones ?? [])" hint="По одному номеру в строке." />@endif<x-ui.button>Сохранить организацию</x-ui.button></form></x-ui.card>@endif
@if($user->isWholesaler() && $organization)<x-ui.card class="mt-5"><h2 class="text-lg font-bold">Коды приглашения</h2><p class="mt-1 text-sm text-muted">Код действует 30 дней и может быть использован одной аптекой.</p>@if(session('invitation_code'))<p class="mt-3 rounded-control bg-brand-50 p-3 font-mono font-bold text-brand-700">{{ session('invitation_code') }}</p>@endif<form method="post" action="{{ route('supplier.invitations.store') }}" class="mt-4">@csrf <x-ui.button>Создать код</x-ui.button></form><div class="mt-4 space-y-2">@foreach($organization->supplierInvitations->whereNull('redeemed_at')->whereNull('revoked_at') as $invitation)@if($invitation->expires_at->isFuture())<form method="post" action="{{ route('supplier.invitations.revoke', $invitation) }}" class="flex items-center justify-between gap-3 border-t border-slate-200 pt-2">@csrf <span class="text-sm text-muted">Код №{{ $invitation->id }} · до {{ $invitation->expires_at->timezone('Asia/Dushanbe')->format('d.m.Y H:i') }}</span><x-ui.button variant="secondary">Отозвать</x-ui.button></form>@endif @endforeach</div></x-ui.card>@endif
</div>
@endsection
