@extends('layouts.app')
@section('content')
<x-ui.page-header title="Подписки пользователей" description="Выдавайте только платные тарифы пользователям аптек."><x-slot:actions><div class="flex gap-3"><a class="text-sm font-semibold text-brand-700 hover:underline" href="{{ route('admin.subscription-prices.edit') }}">Цены тарифов</a><a class="text-sm font-semibold text-brand-700 hover:underline" href="{{ route('admin.users') }}">Пользователи</a></div></x-slot:actions></x-ui.page-header>
<x-ui.card class="mb-6"><form method="post" action="{{ route('admin.subscriptions.store') }}" class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">@csrf
<x-ui.select name="user_id" label="Пользователь аптеки" required><option value="">Выберите пользователя</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(old('user_id', request('user_id')) == $user->id)>{{ $user->name }} · {{ $user->organization?->name }}</option>@endforeach</x-ui.select>
<x-ui.select name="plan" label="Платный тариф" required><option value="">Выберите тариф</option>@foreach($plans as $plan)<option value="{{ $plan->value }}" @selected(old('plan') === $plan->value)>{{ $plan->label() }}</option>@endforeach</x-ui.select>
<x-ui.select name="term" label="Срок" required><option value="">Выберите срок</option>@foreach($terms as $term)<option value="{{ $term->value }}" @selected(old('term') === $term->value)>{{ $term->label() }}</option>@endforeach</x-ui.select>
<x-ui.input name="ends_on" type="date" label="Дата окончания" hint="Только для произвольного срока; дата включается в стоимость." min="{{ now('Asia/Dushanbe')->toDateString() }}" />
<div class="md:col-span-2 xl:col-span-4"><x-ui.button>Выдать подписку</x-ui.button></div></form></x-ui.card>
<div class="table-wrap"><table class="data-table"><thead><tr><th>Пользователь</th><th>Тариф</th><th>Срок</th><th>Период</th><th>Стоимость</th><th>Статус</th></tr></thead><tbody>@forelse($subscriptions as $subscription)<tr><td>{{ $subscription->user->name }}<span class="block text-xs text-muted">{{ $subscription->user->organization?->name }}</span></td><td>{{ $subscription->plan->label() }}</td><td>{{ $subscription->term->label() }}</td><td>{{ $subscription->starts_on->format('d.m.Y') }} — {{ $subscription->ends_on->format('d.m.Y') }}</td><td>{{ $subscription->total_price }} TJS<span class="block text-xs text-muted">{{ $subscription->daily_price }} TJS/день</span></td><td>{{ $subscription->status->label() }}</td></tr>@empty<tr><td colspan="6"><x-ui.empty-state title="Подписок пока нет" /></td></tr>@endforelse</tbody></table></div>
<div class="mt-6">{{ $subscriptions->links() }}</div>
@endsection
