@extends('layouts.app')
@section('content')
<x-ui.page-header title="Платежи за подписки" description="Настройте кошельки и вручную сверяйте переводы с внешним сервисом."><x-slot:actions><a class="text-sm font-semibold text-brand-700 hover:underline" href="{{ route('admin.subscriptions.index') }}">Подписки</a></x-slot:actions></x-ui.page-header>
<x-ui.card class="mb-6"><h2 class="text-lg font-semibold">Способы оплаты</h2><form method="post" action="{{ route('admin.subscription-payments.methods.update') }}" class="mt-4 grid gap-4 md:grid-cols-3">@csrf @method('PATCH')
@foreach($paymentMethodCases as $method) @php($setting = $methods->get($method->value))
<fieldset class="space-y-3 rounded-control border border-slate-200 p-3"><legend class="px-1 text-sm font-semibold">{{ $method->label() }}</legend><label class="flex min-h-10 items-center gap-2 text-sm"><input type="hidden" name="methods[{{ $loop->index }}][is_enabled]" value="0"><input type="checkbox" name="methods[{{ $loop->index }}][is_enabled]" value="1" @checked(old("methods.{$loop->index}.is_enabled", $setting?->is_enabled))> Доступен аптекам</label><input type="hidden" name="methods[{{ $loop->index }}][method]" value="{{ $method->value }}"><x-ui.input name="methods[{{ $loop->index }}][wallet_number]" label="Номер кошелька" value="{{ old("methods.{$loop->index}.wallet_number", $setting?->wallet_number) }}" /><x-ui.textarea name="methods[{{ $loop->index }}][instructions]" label="Инструкция на русском" value="{{ old("methods.{$loop->index}.instructions", $setting?->instructions) }}" /></fieldset>
@endforeach
<div class="md:col-span-3"><x-ui.button>Сохранить способы оплаты</x-ui.button></div></form></x-ui.card>
<div class="table-wrap"><table class="data-table"><thead><tr><th>Аптека</th><th>Квитанция и перевод</th><th>Сумма</th><th>Статус</th><th>Решение</th></tr></thead><tbody>@forelse($paymentRequests as $paymentRequest)<tr><td>{{ $paymentRequest->organization->name }}<span class="block text-xs text-muted">{{ $paymentRequest->user->name }}</span></td><td>{{ $paymentRequest->payment_method?->label() }} · {{ $paymentRequest->recipient_wallet }}<span class="block text-xs text-muted">{{ $paymentRequest->transfer_reference }} от {{ $paymentRequest->transferred_on?->format('d.m.Y') }}</span>@if($paymentRequest->receipt_path)<a class="text-xs font-semibold text-brand-700 hover:underline" href="{{ route('payment-requests.receipt', $paymentRequest) }}">Открыть квитанцию</a>@endif</td><td>{{ $paymentRequest->amount }} TJS</td><td><x-ui.status-badge :status="$paymentRequest->status" />@if($paymentRequest->rejection_reason)<span class="block text-xs text-danger">{{ $paymentRequest->rejection_reason }}</span>@endif</td><td>@if($paymentRequest->status === 'pending')<form method="post" action="{{ route('admin.subscription-payments.review', $paymentRequest) }}" class="grid gap-2">@csrf <x-ui.input name="verified_amount" label="Сверенная сумма" required /><x-ui.input name="verified_reference" label="Внешний номер" required /><x-ui.button name="decision" value="approve">Подтвердить</x-ui.button><x-ui.textarea name="rejection_reason" label="Причина отклонения" /><x-ui.button variant="danger" name="decision" value="reject">Отклонить</x-ui.button></form>@else<span class="text-sm text-muted">{{ $paymentRequest->reviewer?->name }}<br>{{ $paymentRequest->reviewed_at?->format('d.m.Y H:i') }}</span>@endif</td></tr>@empty<tr><td colspan="5"><x-ui.empty-state title="Заявок на оплату пока нет" /></td></tr>@endforelse</tbody></table></div><div class="mt-6">{{ $paymentRequests->links() }}</div>
@endsection
