@extends('layouts.app')

@section('content')
@php
    $isProvider = $type === \App\Enums\OrganizationType::Wholesaler;
    $prefix = $isProvider ? 'admin.providers' : 'admin.pharmacies';
@endphp
<x-ui.page-header :title="'Редактирование: '.$organization->name" description="Контакт организации не связан с телефонами отдельных учётных записей.">
    <x-slot:actions><x-ui.button variant="ghost" :href="route($prefix.'.show', $organization)">К карточке</x-ui.button></x-slot:actions>
</x-ui.page-header>
<form method="post" action="{{ route($prefix.'.update', $organization) }}" class="space-y-6">@csrf @method('PATCH')
    <x-ui.card><div class="grid gap-4 md:grid-cols-2"><x-ui.input name="name" label="Название" :value="$organization->name" required /><x-ui.input name="city" label="Город" :value="$organization->city" /><x-ui.input name="phone" label="Телефон организации" :value="$organization->phone" placeholder="+992901234567" /><x-ui.select name="status" label="Статус"><option value="active" @selected(old('status', $organization->status) === 'active')>Активна</option><option value="blocked" @selected(old('status', $organization->status) === 'blocked')>Заблокирована</option></x-ui.select>@if($isProvider)<x-ui.select name="supplier_mode" label="Режим поставщика"><option value="supplier" @selected(old('supplier_mode', $organization->supplier_mode) === 'supplier')>Поставщик</option><option value="both" @selected(old('supplier_mode', $organization->supplier_mode) === 'both')>Покупатель и поставщик</option></x-ui.select><x-ui.input name="minimum_order" type="number" min="0" step="0.01" label="Минимальный заказ" :value="$organization->minimum_order" required /><div class="md:col-span-2"><x-ui.textarea name="delivery_conditions" label="Условия доставки" :value="$organization->delivery_conditions" /></div><x-ui.input name="contact_name" label="Контактное лицо" :value="$organization->contact_name" /><x-ui.input name="contact_email" type="email" label="Контактный email" :value="$organization->contact_email" /><x-ui.input name="whatsapp_phone" label="WhatsApp" :value="$organization->whatsapp_phone" /><x-ui.textarea name="additional_phones" label="Дополнительные телефоны" :value="implode("\n", $organization->additional_phones ?? [])" hint="По одному номеру в строке." />@endif</div><div class="mt-5"><x-ui.button>Сохранить организацию</x-ui.button></div></x-ui.card>
</form>
<section class="mt-6 space-y-4"><h2 class="text-xl font-bold">Учётные записи</h2>@forelse($organization->users as $user)<x-ui.card><form method="post" action="{{ route($prefix.'.accounts.update', [$organization, $user]) }}" class="space-y-4">@csrf @method('PATCH')<div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><x-ui.input name="name" label="Имя" :value="$user->name" required /><x-ui.input name="email" type="email" label="Email" :value="$user->email" /><x-ui.input name="phone" label="Телефон" :value="$user->phone" placeholder="+992901234567" /><x-ui.select name="is_blocked" label="Состояние"><option value="0" @selected(! $user->is_blocked)>Активна</option><option value="1" @selected($user->is_blocked)>Заблокирована</option></x-ui.select></div><div class="mt-4"><x-ui.button variant="secondary">Сохранить учётную запись</x-ui.button></div></form></x-ui.card>@empty<x-ui.empty-state title="Нет связанных учётных записей" />@endforelse</section>
<x-ui.card class="mt-6 border-red-200"><h2 class="text-lg font-bold text-danger">Архивация</h2><p class="mt-1 text-sm text-muted">Организация и история останутся в системе, но статус станет «Заблокирована», а все связанные учётные записи будут заблокированы.</p><form method="post" action="{{ route($prefix.'.archive', $organization) }}" class="mt-4" onsubmit="return confirm('Архивировать организацию и заблокировать все связанные учётные записи?')">@csrf <x-ui.button variant="danger">Архивировать организацию</x-ui.button></form></x-ui.card>
@endsection
