<!doctype html>
<html lang="ru">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>OAPTEKA</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body>
<header class="border-b border-slate-200 bg-white"><div class="page-container flex min-h-16 flex-wrap items-center justify-between gap-3 py-3">
<a href="{{ route('catalog') }}" class="flex items-center gap-2 text-lg font-bold tracking-tight text-brand-700"><span class="grid size-8 place-items-center rounded-control bg-brand-600 text-sm text-white" aria-hidden="true">+</span> OAPTEKA</a>
<details class="group md:hidden"><summary class="cursor-pointer list-none rounded-control border border-slate-300 px-3 py-2 text-sm font-medium">Меню</summary><nav class="absolute right-4 z-10 mt-2 flex w-60 flex-col gap-1 rounded-panel border border-slate-200 bg-white p-2 shadow-panel"><a class="rounded-control px-3 py-2 hover:bg-brand-50" href="{{ route('catalog') }}">Каталог</a>@auth <a class="rounded-control px-3 py-2 hover:bg-brand-50" href="{{ route('dashboard') }}">Кабинет</a><a class="rounded-control px-3 py-2 hover:bg-brand-50" href="{{ route('cart') }}">Корзина</a><a class="rounded-control px-3 py-2 hover:bg-brand-50" href="{{ route('orders.index') }}">Заказы</a>@if(auth()->user()->isAdmin())<a class="rounded-control px-3 py-2 hover:bg-brand-50" href="{{ route('admin.index') }}">Администрирование</a>@endif<form method="post" action="{{ route('logout') }}">@csrf <button class="w-full rounded-control px-3 py-2 text-left text-danger hover:bg-red-50">Выйти</button></form>@else <a class="rounded-control px-3 py-2 hover:bg-brand-50" href="{{ route('login') }}">Войти</a><a class="rounded-control px-3 py-2 hover:bg-brand-50" href="{{ route('register') }}">Регистрация</a>@endauth</nav></details>
<nav class="hidden items-center gap-1 text-sm md:flex"><a class="rounded-control px-3 py-2 {{ request()->routeIs('catalog') ? 'bg-brand-50 font-semibold text-brand-700' : 'text-slate-600 hover:bg-slate-50' }}" href="{{ route('catalog') }}">Каталог</a>@auth <a class="rounded-control px-3 py-2 {{ request()->routeIs('dashboard') ? 'bg-brand-50 font-semibold text-brand-700' : 'text-slate-600 hover:bg-slate-50' }}" href="{{ route('dashboard') }}">Кабинет</a><a class="rounded-control px-3 py-2 {{ request()->routeIs('profile.*') ? 'bg-brand-50 font-semibold text-brand-700' : 'text-slate-600 hover:bg-slate-50' }}" href="{{ route('profile.edit') }}">Профиль</a>@if(auth()->user()->canBuy())<a class="rounded-control px-3 py-2 text-slate-600 hover:bg-slate-50" href="{{ route('cart') }}">Корзина</a>@endif<a class="rounded-control px-3 py-2 text-slate-600 hover:bg-slate-50" href="{{ route('orders.index') }}">Заказы</a>@if(auth()->user()->isAdmin())<a class="rounded-control px-3 py-2 {{ request()->routeIs('admin.*') ? 'bg-brand-50 font-semibold text-brand-700' : 'text-slate-600 hover:bg-slate-50' }}" href="{{ route('admin.index') }}">Администрирование</a>@endif <span class="ml-2 border-l border-slate-200 pl-3 text-slate-500">{{ auth()->user()->name }}</span><form method="post" action="{{ route('logout') }}">@csrf <button class="rounded-control px-3 py-2 text-danger hover:bg-red-50">Выйти</button></form>@else <a class="rounded-control px-3 py-2 text-slate-600 hover:bg-slate-50" href="{{ route('login') }}">Войти</a><a class="rounded-control bg-brand-600 px-3 py-2 font-medium text-white hover:bg-brand-700" href="{{ route('register') }}">Регистрация</a>@endauth</nav>
</div></header>
<main class="page-container {{ request()->routeIs('login', 'login.otp.form', 'login.session.confirmation', 'admin.login', 'provider.login', 'register') ? 'max-w-lg py-10 sm:py-16' : 'py-6 sm:py-8' }}"><div class="mb-5 space-y-3" aria-live="polite">@if(session('success'))<x-ui.alert type="success">{{ session('success') }}</x-ui.alert>@endif @if(session('warning'))<x-ui.alert type="warning">{{ session('warning') }}</x-ui.alert>@endif @if($errors->any())<x-ui.alert type="danger">{{ $errors->first() }}</x-ui.alert>@endif</div>@yield('content')</main>
</body></html>
